version: "3.9"

services:
   ducthanh-web:
      restart: always
      build:
         context: ./
         dockerfile: Dockerfile.dev
      container_name: web
      volumes:
         - ./:/app
         - /app/node_modules
      ports:
         - 5000:5000
      depends_on:
         - mongodb
      environment:
         NODE_ENV: ${NODE_ENV}
         MONGO_URI: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb
      networks:
         - ducthanh

   mongodb:
      image: mongo
      restart: always
      ports:
         - 27017:27017
      environment:
         MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
         MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      volumes:
         - mongodb-data:/data/db
      networks:
         - ducthanh
   mongo-express:
      image: mongo-express
      depends_on:
         - mongodb
      ports:
         - 8081:8081
      environment:
         ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
         ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
         ME_CONFIG_MONGODB_SERVER: mongodb
         ME_CONFIG_BASICAUTH_USERNAME: admin
         ME_CONFIG_BASICAUTH_PASSWORD: admin123456
      volumes:
         - mongodb-data:/var/lib/docker/volumes/web_mongodb-data/_data
      networks:
         - ducthanh

networks:
   ducthanh:
      driver: bridge

volumes:
   mongodb-data:
      driver: local
